### PR TITLE
main.py

### PR DESCRIPTION
**Pull request by ImMcHe**
LittleMan V1.1

For this update, fixed:

Randomizes the hello command=True

### CODE REVIEW

**Review by Quezard — CHANGES_REQUESTED** [review]
why is there 2 hello message?
helloMessage[helloMessage[random.randint(0,2)]

**Comment by ImMcHe** [comment]
helloMessage=["Hello! Good to see you.","Hi!","Hello! I'm Litte Man"]

It will randomize the hello message when you type in !hello
Also the random is the randomization. It will give a value from 0-2, fits the range of the index, science the range of the length of the index is 3, and the max value of the array is 2.

**Comment by Quezard** [comment]
yes, but **helloMessage[random.randint(0,2)]** is enough to do that.
why do you need **helloMessage[helloMessage[random.randint(0,2)]**?

**Comment by ImMcHe** [comment]
Ok, I'll fix that.

**Review by Quezard — APPROVED** [review]
approved

**Pull request merged**
