### PR TITLE
main.py

### PR DESCRIPTION
**Pull request by ImMcHe**
Little Man update v1.3:

Added:
● Fixed isScriptGood command

(I'm not sure if it works or not.)

### CODE REVIEW

**Review by Quezard — CHANGES_REQUESTED** [review]
You used lists in a list to store the languages and description.
However, you have to loop over the entire list every time to find the index.
which takes O(n) time, can you change it to a python dictionary to store the pairs?
use the language as the key and description as value.
it should be O(1) instead of O(n).

In addition, the language check is case sensitive, can you change it to non-case sensitive?
also add args=None at the function header because there will be an error if no argument is provided. If you are not sure about this, check the resolve function header.

**Comment by ImMcHe** [comment]
Fixed error.

**Comment by Quezard** [comment]
this is still case sensitive.
and you are still using a 2d array.

**Comment by ImMcHe** [comment]
Yes, but it is a different type of 2d array.
I am using 2 arrays for the 2d array.

**Comment by ImMcHe** [comment]
Sorry, I don't know Python too much. I don't know what a dictionary is so I stored it as a file.

**Pull request merged**
